// Generated by CoffeeScript 1.8.0
var async, new_async_file, new_waterfall;

new_async_file = "ASYNC";

new_waterfall = "ASYNC WATERFALL";

async = require('async');

async.waterfall([
  function(callback) {
    return callback(null, "one", "two");
  }, function(arg1, arg2, callback) {
    return callback(null, "three");
  }, function(arg1, callback) {
    return callback(null, "done");
  }
], function(err, result) {
  return console.log(result);
});
